name: iOS CI - Banking Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test Default Scheme
    runs-on: macos-latest  # Runs on a virtual Mac

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # CRITICAL: Gitleaks needs full history to scan properly

      # NEW SECURITY: Checks for Token/API Keys
      - name: Security Scan - Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Unit Tests
        # This is the magic command that runs your TDD tests
        run: |
          xcodebuild test \
            -project BankCore.xcodeproj \
            -scheme BankCore \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            clean test
